sonar.projectKey=conformance-nextjs-v2
sonar.projectName=conformance-nextjs-v2
sonar.exclusions=.pipeline/**,node_modules/**,vendor/**,target/**,dist/**,build/**,.next/**,coverage/**
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts
sonar.cpd.exclusions=**/*.spec.ts,**/*.test.ts
